# Generated by Django 4.0.5 on 2022-07-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='keyword',
        ),
        migrations.AddField(
            model_name='qna',
            name='keywords',
            field=models.ManyToManyField(to='keywords.keyword'),
        ),
    ]
