# Generated by Django 4.0.5 on 2022-07-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('main', '0003_alter_qna_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='keywords.keyword'),
        ),
    ]
