# Generated by Django 4.0.6 on 2022-07-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_chatbot', '0005_auto_20210502_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='simple_chatbot.tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='method',
            field=models.CharField(choices=[('main.responses.GreetingResponse', 'Greeting'), ('main.responses.GoodbyeResponse', 'Goodbye'), ('main.responses.LocatedResponse', 'location'), ('main.responses.establishedResponce', 'established'), ('main.responses.nirfrank', 'nirf'), ('main.responses.founder', 'founder'), ('main.responses.Principle', 'Principle'), ('main.responses.website', 'website'), ('main.responses.distMangalore', 'distMangalore'), ('main.responses.Alumnis', 'Alumnis'), ('main.responses.officialMail', 'officialMail'), ('main.responses.girlsHostel', 'girlsHostel'), ('main.responses.boysHostel', 'boysHostel'), ('main.responses.TransportationFacilities', 'TransportationFacilities'), ('main.responses.CanteenFacilities', 'CanteenFacilities'), ('main.responses.HealthcareFacilities', 'HealthcareFacilities'), ('main.responses.contactNumber', 'contactNumber'), ('main.responses.CampusContacts', 'CampusContacts'), ('main.responses.Btechprogrammes', 'Btechprogrammes'), ('main.responses.CompaniesNo', 'CompaniesNo'), ('main.responses.HighestPackage', 'HighestPackage'), ('main.responses.studentsPlaced', 'studentsPlaced'), ('main.responses.averagePackage', 'averagePackage'), ('main.responses.placementsUpdates', 'placementsUpdates'), ('main.responses.placementTrainingName', 'placementTrainingName'), ('main.responses.PlacementHead', 'PlacementHead'), ('main.responses.QualificationPlacementHead', 'QualificationPlacementHead'), ('main.responses.ContactPlacement', 'ContactPlacement'), ('main.responses.cgpaPlacement', 'cgpaPlacement'), ('main.responses.cgpasuperdream', 'cgpasuperdream'), ('main.responses.recruitmentPolicy', 'recruitmentPolicy'), ('main.responses.ProgramsAvailable', 'ProgramsAvailable'), ('main.responses.CoursesAvailablePostgraduate', 'CoursesAvailablePostgraduate'), ('main.responses.CoursesAvailableDoctoral', 'CoursesAvailableDoctoral'), ('main.responses.CoursesAvailableBTECH', 'CoursesAvailableBTECH'), ('main.responses.CoursesAvailableMTECH', 'CoursesAvailableMTECH'), ('main.responses.eligibilitycriteriaBTECH', 'eligibilitycriteriaBTECH'), ('main.responses.admissionprocedureBTECH', 'admissionprocedureBTECH'), ('main.responses.generalcategoryBTECH', 'generalcategoryBTECH'), ('main.responses.NRIcategoryBTECH', 'NRIcategoryBTECH'), ('main.responses.classescommence', 'classescommence'), ('main.responses.accommodation', 'accommodation'), ('main.responses.foodfacilities', 'foodfacilities'), ('main.responses.Feestructure', 'Feestructure'), ('main.responses.scholarshipcategory', 'scholarshipcategory'), ('main.responses.generalcategory', 'generalcategory'), ('main.responses.NRIcategory', 'NRIcategory'), ('main.responses.libraryfacilities', 'libraryfacilities'), ('main.responses.Hostelfacilities', 'Hostelfacilities'), ('main.responses.facultymembersoftheplacementdepartment', 'facultymembersoftheplacementdepartment'), ('main.responses.websiteregardingplacements', 'websiteregardingplacements'), ('main.responses.emailidoftheplacementdepartment', 'emailidoftheplacementdepartment'), ('main.responses.placementsessionusuallystart', 'placementsessionusuallystart'), ('main.responses.activitiesconducted', 'activitiesconducted'), ('main.responses.WhatNmamit', 'WhatNmamit'), ('main.responses.howru', 'howru'), ('main.responses.thank', 'thank'), ('main.responses.food', 'food'), ('main.responses.whatcan', 'whatcan'), ('main.responses.ecHod', 'ecHod'), ('main.responses.ecInfo', 'ecInfo'), ('main.responses.aiDaInfo', 'aiDaInfo'), ('main.responses.aiMlInfo', 'aiMlInfo'), ('main.responses.aiMlHod', 'aiMlHod'), ('main.responses.bioInfo', 'bioInfo'), ('main.responses.bioHod', 'bioHod'), ('main.responses.civilInfo', 'civilInfo'), ('main.responses.civilHod', 'civilHod'), ('main.responses.comCommuInfo', 'comCommuInfo'), ('main.responses.comCommuHod', 'comCommuHod'), ('main.responses.csInfo', 'csInfo'), ('main.responses.csHod', 'csHod'), ('main.responses.eeInfo', 'eeInfo'), ('main.responses.eeHod', 'eeHod'), ('main.responses.isInfo', 'isInfo'), ('main.responses.isHod', 'isHod'), ('main.responses.mechInfo', 'mechInfo'), ('main.responses.mechHod', 'mechHod'), ('main.responses.roboInfo', 'roboInfo'), ('main.responses.roboHod', 'roboHod'), ('main.responses.creaters', 'creaters')], max_length=120, unique=True, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='token',
            name='patterns',
            field=models.ManyToManyField(blank=True, editable=False, related_name='%(class)ss', to='simple_chatbot.pattern'),
        ),
        migrations.AlterField(
            model_name='usermessageinput',
            name='correct_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_corrected', to='simple_chatbot.tag', verbose_name='correct tag'),
        ),
        migrations.AlterField(
            model_name='usermessageinput',
            name='identified_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_identified', to='simple_chatbot.tag', verbose_name='identified tag'),
        ),
    ]
